/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'Garfield_system'
 * SOPC Builder design path: ../../Garfield_system.sopcinfo
 *
 * Generated: Wed Jun 07 14:02:01 GMT+01:00 2017
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00040820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 2
#define ALT_CPU_CPU_ID_VALUE 0x00000003
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x14
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x14
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x000a0000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00040820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 2
#define NIOS2_CPU_ID_VALUE 0x00000003
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x14
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x14
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x000a0000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_EPCS_FLASH_CONTROLLER
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_MAILBOX_SIMPLE
#define __ALTERA_AVALON_MUTEX
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __I2C_OPENCORES
#define __PWM_GENERATOR
#define __ROTARY_ENCODER


/*
 * Drive_PWM configuration
 *
 */

#define ALT_MODULE_CLASS_Drive_PWM PWM_Generator
#define DRIVE_PWM_BASE 0x80
#define DRIVE_PWM_IRQ -1
#define DRIVE_PWM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DRIVE_PWM_NAME "/dev/Drive_PWM"
#define DRIVE_PWM_SPAN 8
#define DRIVE_PWM_TYPE "PWM_Generator"


/*
 * Garfield_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_Garfield_GPIO altera_avalon_pio
#define GARFIELD_GPIO_BASE 0x70
#define GARFIELD_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define GARFIELD_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GARFIELD_GPIO_CAPTURE 0
#define GARFIELD_GPIO_DATA_WIDTH 8
#define GARFIELD_GPIO_DO_TEST_BENCH_WIRING 0
#define GARFIELD_GPIO_DRIVEN_SIM_VALUE 0
#define GARFIELD_GPIO_EDGE_TYPE "NONE"
#define GARFIELD_GPIO_FREQ 50000000
#define GARFIELD_GPIO_HAS_IN 0
#define GARFIELD_GPIO_HAS_OUT 1
#define GARFIELD_GPIO_HAS_TRI 0
#define GARFIELD_GPIO_IRQ -1
#define GARFIELD_GPIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GARFIELD_GPIO_IRQ_TYPE "NONE"
#define GARFIELD_GPIO_NAME "/dev/Garfield_GPIO"
#define GARFIELD_GPIO_RESET_VALUE 0
#define GARFIELD_GPIO_SPAN 16
#define GARFIELD_GPIO_TYPE "altera_avalon_pio"


/*
 * Garfield_lighting configuration
 *
 */

#define ALT_MODULE_CLASS_Garfield_lighting altera_avalon_pio
#define GARFIELD_LIGHTING_BASE 0x60
#define GARFIELD_LIGHTING_BIT_CLEARING_EDGE_REGISTER 0
#define GARFIELD_LIGHTING_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GARFIELD_LIGHTING_CAPTURE 0
#define GARFIELD_LIGHTING_DATA_WIDTH 4
#define GARFIELD_LIGHTING_DO_TEST_BENCH_WIRING 0
#define GARFIELD_LIGHTING_DRIVEN_SIM_VALUE 0
#define GARFIELD_LIGHTING_EDGE_TYPE "NONE"
#define GARFIELD_LIGHTING_FREQ 50000000
#define GARFIELD_LIGHTING_HAS_IN 0
#define GARFIELD_LIGHTING_HAS_OUT 1
#define GARFIELD_LIGHTING_HAS_TRI 0
#define GARFIELD_LIGHTING_IRQ -1
#define GARFIELD_LIGHTING_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GARFIELD_LIGHTING_IRQ_TYPE "NONE"
#define GARFIELD_LIGHTING_NAME "/dev/Garfield_lighting"
#define GARFIELD_LIGHTING_RESET_VALUE 0
#define GARFIELD_LIGHTING_SPAN 16
#define GARFIELD_LIGHTING_TYPE "altera_avalon_pio"


/*
 * Onboard_Button configuration
 *
 */

#define ALT_MODULE_CLASS_Onboard_Button altera_avalon_pio
#define ONBOARD_BUTTON_BASE 0x100c0
#define ONBOARD_BUTTON_BIT_CLEARING_EDGE_REGISTER 1
#define ONBOARD_BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ONBOARD_BUTTON_CAPTURE 1
#define ONBOARD_BUTTON_DATA_WIDTH 2
#define ONBOARD_BUTTON_DO_TEST_BENCH_WIRING 0
#define ONBOARD_BUTTON_DRIVEN_SIM_VALUE 0
#define ONBOARD_BUTTON_EDGE_TYPE "FALLING"
#define ONBOARD_BUTTON_FREQ 50000000
#define ONBOARD_BUTTON_HAS_IN 1
#define ONBOARD_BUTTON_HAS_OUT 0
#define ONBOARD_BUTTON_HAS_TRI 0
#define ONBOARD_BUTTON_IRQ -1
#define ONBOARD_BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONBOARD_BUTTON_IRQ_TYPE "NONE"
#define ONBOARD_BUTTON_NAME "/dev/Onboard_Button"
#define ONBOARD_BUTTON_RESET_VALUE 0
#define ONBOARD_BUTTON_SPAN 16
#define ONBOARD_BUTTON_TYPE "altera_avalon_pio"


/*
 * Onboard_DipSW configuration
 *
 */

#define ALT_MODULE_CLASS_Onboard_DipSW altera_avalon_pio
#define ONBOARD_DIPSW_BASE 0x10080
#define ONBOARD_DIPSW_BIT_CLEARING_EDGE_REGISTER 1
#define ONBOARD_DIPSW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ONBOARD_DIPSW_CAPTURE 1
#define ONBOARD_DIPSW_DATA_WIDTH 4
#define ONBOARD_DIPSW_DO_TEST_BENCH_WIRING 0
#define ONBOARD_DIPSW_DRIVEN_SIM_VALUE 0
#define ONBOARD_DIPSW_EDGE_TYPE "ANY"
#define ONBOARD_DIPSW_FREQ 50000000
#define ONBOARD_DIPSW_HAS_IN 1
#define ONBOARD_DIPSW_HAS_OUT 0
#define ONBOARD_DIPSW_HAS_TRI 0
#define ONBOARD_DIPSW_IRQ -1
#define ONBOARD_DIPSW_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONBOARD_DIPSW_IRQ_TYPE "NONE"
#define ONBOARD_DIPSW_NAME "/dev/Onboard_DipSW"
#define ONBOARD_DIPSW_RESET_VALUE 0
#define ONBOARD_DIPSW_SPAN 16
#define ONBOARD_DIPSW_TYPE "altera_avalon_pio"


/*
 * Onboard_LED configuration
 *
 */

#define ALT_MODULE_CLASS_Onboard_LED altera_avalon_pio
#define ONBOARD_LED_BASE 0x10050
#define ONBOARD_LED_BIT_CLEARING_EDGE_REGISTER 0
#define ONBOARD_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ONBOARD_LED_CAPTURE 0
#define ONBOARD_LED_DATA_WIDTH 8
#define ONBOARD_LED_DO_TEST_BENCH_WIRING 0
#define ONBOARD_LED_DRIVEN_SIM_VALUE 0
#define ONBOARD_LED_EDGE_TYPE "NONE"
#define ONBOARD_LED_FREQ 50000000
#define ONBOARD_LED_HAS_IN 0
#define ONBOARD_LED_HAS_OUT 1
#define ONBOARD_LED_HAS_TRI 0
#define ONBOARD_LED_IRQ -1
#define ONBOARD_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONBOARD_LED_IRQ_TYPE "NONE"
#define ONBOARD_LED_NAME "/dev/Onboard_LED"
#define ONBOARD_LED_RESET_VALUE 0
#define ONBOARD_LED_SPAN 16
#define ONBOARD_LED_TYPE "altera_avalon_pio"


/*
 * Rotary_Encoder_0 configuration
 *
 */

#define ALT_MODULE_CLASS_Rotary_Encoder_0 Rotary_Encoder
#define ROTARY_ENCODER_0_BASE 0xa0
#define ROTARY_ENCODER_0_IRQ -1
#define ROTARY_ENCODER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ROTARY_ENCODER_0_NAME "/dev/Rotary_Encoder_0"
#define ROTARY_ENCODER_0_SPAN 8
#define ROTARY_ENCODER_0_TYPE "Rotary_Encoder"


/*
 * Steering_PWM configuration
 *
 */

#define ALT_MODULE_CLASS_Steering_PWM PWM_Generator
#define STEERING_PWM_BASE 0x90
#define STEERING_PWM_IRQ -1
#define STEERING_PWM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define STEERING_PWM_NAME "/dev/Steering_PWM"
#define STEERING_PWM_SPAN 8
#define STEERING_PWM_TYPE "PWM_Generator"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_LEGACY_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_nios2"
#define ALT_STDERR_BASE 0x41000
#define ALT_STDERR_DEV jtag_uart_nios2
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_nios2"
#define ALT_STDIN_BASE 0x41000
#define ALT_STDIN_DEV jtag_uart_nios2
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_nios2"
#define ALT_STDOUT_BASE 0x41000
#define ALT_STDOUT_DEV jtag_uart_nios2
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "Garfield_system"


/*
 * epcs_flash_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_epcs_flash_controller_0 altera_avalon_epcs_flash_controller
#define EPCS_FLASH_CONTROLLER_0_BASE 0xa0000
#define EPCS_FLASH_CONTROLLER_0_IRQ 1
#define EPCS_FLASH_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EPCS_FLASH_CONTROLLER_0_NAME "/dev/epcs_flash_controller_0"
#define EPCS_FLASH_CONTROLLER_0_REGISTER_OFFSET 1024
#define EPCS_FLASH_CONTROLLER_0_SPAN 2048
#define EPCS_FLASH_CONTROLLER_0_TYPE "altera_avalon_epcs_flash_controller"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_0_NIOS2
#define ALT_TIMESTAMP_CLK none


/*
 * i2c_opencores_0 configuration
 *
 */

#define ALT_MODULE_CLASS_i2c_opencores_0 i2c_opencores
#define I2C_OPENCORES_0_BASE 0x8000
#define I2C_OPENCORES_0_IRQ 10
#define I2C_OPENCORES_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define I2C_OPENCORES_0_NAME "/dev/i2c_opencores_0"
#define I2C_OPENCORES_0_SPAN 32
#define I2C_OPENCORES_0_TYPE "i2c_opencores"


/*
 * jtag_uart_nios2 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_nios2 altera_avalon_jtag_uart
#define JTAG_UART_NIOS2_BASE 0x41000
#define JTAG_UART_NIOS2_IRQ 0
#define JTAG_UART_NIOS2_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NIOS2_NAME "/dev/jtag_uart_nios2"
#define JTAG_UART_NIOS2_READ_DEPTH 64
#define JTAG_UART_NIOS2_READ_THRESHOLD 8
#define JTAG_UART_NIOS2_SPAN 8
#define JTAG_UART_NIOS2_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_NIOS2_WRITE_DEPTH 64
#define JTAG_UART_NIOS2_WRITE_THRESHOLD 8


/*
 * mailbox_arm2nios_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mailbox_arm2nios_0 altera_avalon_mailbox_simple
#define MAILBOX_ARM2NIOS_0_BASE 0xc0
#define MAILBOX_ARM2NIOS_0_IRQ 3
#define MAILBOX_ARM2NIOS_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MAILBOX_ARM2NIOS_0_NAME "/dev/mailbox_arm2nios_0"
#define MAILBOX_ARM2NIOS_0_SPAN 16
#define MAILBOX_ARM2NIOS_0_TYPE "altera_avalon_mailbox_simple"


/*
 * mailbox_nios2arm_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mailbox_nios2arm_0 altera_avalon_mailbox_simple
#define MAILBOX_NIOS2ARM_0_BASE 0x10030
#define MAILBOX_NIOS2ARM_0_IRQ -1
#define MAILBOX_NIOS2ARM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAILBOX_NIOS2ARM_0_NAME "/dev/mailbox_nios2arm_0"
#define MAILBOX_NIOS2ARM_0_SPAN 16
#define MAILBOX_NIOS2ARM_0_TYPE "altera_avalon_mailbox_simple"


/*
 * onchip_memory2_nios2 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_nios2 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_NIOS2_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_NIOS2_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_NIOS2_BASE 0x20000
#define ONCHIP_MEMORY2_NIOS2_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_NIOS2_DUAL_PORT 0
#define ONCHIP_MEMORY2_NIOS2_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_NIOS2_INIT_CONTENTS_FILE "Garfield_system_onchip_memory2_nios2"
#define ONCHIP_MEMORY2_NIOS2_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_NIOS2_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_NIOS2_IRQ -1
#define ONCHIP_MEMORY2_NIOS2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_NIOS2_NAME "/dev/onchip_memory2_nios2"
#define ONCHIP_MEMORY2_NIOS2_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_NIOS2_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_NIOS2_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_NIOS2_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_NIOS2_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_NIOS2_SIZE_VALUE 131072
#define ONCHIP_MEMORY2_NIOS2_SPAN 131072
#define ONCHIP_MEMORY2_NIOS2_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_NIOS2_WRITABLE 1


/*
 * shared_memory_master_hps_0 configuration
 *
 */

#define ALT_MODULE_CLASS_shared_memory_master_hps_0 altera_avalon_onchip_memory2
#define SHARED_MEMORY_MASTER_HPS_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SHARED_MEMORY_MASTER_HPS_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SHARED_MEMORY_MASTER_HPS_0_BASE 0x60000
#define SHARED_MEMORY_MASTER_HPS_0_CONTENTS_INFO ""
#define SHARED_MEMORY_MASTER_HPS_0_DUAL_PORT 0
#define SHARED_MEMORY_MASTER_HPS_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SHARED_MEMORY_MASTER_HPS_0_INIT_CONTENTS_FILE "Garfield_system_shared_memory_master_hps_0"
#define SHARED_MEMORY_MASTER_HPS_0_INIT_MEM_CONTENT 1
#define SHARED_MEMORY_MASTER_HPS_0_INSTANCE_ID "NONE"
#define SHARED_MEMORY_MASTER_HPS_0_IRQ -1
#define SHARED_MEMORY_MASTER_HPS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SHARED_MEMORY_MASTER_HPS_0_NAME "/dev/shared_memory_master_hps_0"
#define SHARED_MEMORY_MASTER_HPS_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SHARED_MEMORY_MASTER_HPS_0_RAM_BLOCK_TYPE "AUTO"
#define SHARED_MEMORY_MASTER_HPS_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SHARED_MEMORY_MASTER_HPS_0_SINGLE_CLOCK_OP 0
#define SHARED_MEMORY_MASTER_HPS_0_SIZE_MULTIPLE 1
#define SHARED_MEMORY_MASTER_HPS_0_SIZE_VALUE 2048
#define SHARED_MEMORY_MASTER_HPS_0_SPAN 2048
#define SHARED_MEMORY_MASTER_HPS_0_TYPE "altera_avalon_onchip_memory2"
#define SHARED_MEMORY_MASTER_HPS_0_WRITABLE 1


/*
 * shared_memory_master_nios_0 configuration
 *
 */

#define ALT_MODULE_CLASS_shared_memory_master_nios_0 altera_avalon_onchip_memory2
#define SHARED_MEMORY_MASTER_NIOS_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SHARED_MEMORY_MASTER_NIOS_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SHARED_MEMORY_MASTER_NIOS_0_BASE 0x90000
#define SHARED_MEMORY_MASTER_NIOS_0_CONTENTS_INFO ""
#define SHARED_MEMORY_MASTER_NIOS_0_DUAL_PORT 0
#define SHARED_MEMORY_MASTER_NIOS_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SHARED_MEMORY_MASTER_NIOS_0_INIT_CONTENTS_FILE "Garfield_system_shared_memory_master_nios_0"
#define SHARED_MEMORY_MASTER_NIOS_0_INIT_MEM_CONTENT 1
#define SHARED_MEMORY_MASTER_NIOS_0_INSTANCE_ID "NONE"
#define SHARED_MEMORY_MASTER_NIOS_0_IRQ -1
#define SHARED_MEMORY_MASTER_NIOS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SHARED_MEMORY_MASTER_NIOS_0_NAME "/dev/shared_memory_master_nios_0"
#define SHARED_MEMORY_MASTER_NIOS_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SHARED_MEMORY_MASTER_NIOS_0_RAM_BLOCK_TYPE "AUTO"
#define SHARED_MEMORY_MASTER_NIOS_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SHARED_MEMORY_MASTER_NIOS_0_SINGLE_CLOCK_OP 0
#define SHARED_MEMORY_MASTER_NIOS_0_SIZE_MULTIPLE 1
#define SHARED_MEMORY_MASTER_NIOS_0_SIZE_VALUE 2048
#define SHARED_MEMORY_MASTER_NIOS_0_SPAN 2048
#define SHARED_MEMORY_MASTER_NIOS_0_TYPE "altera_avalon_onchip_memory2"
#define SHARED_MEMORY_MASTER_NIOS_0_WRITABLE 1


/*
 * shared_memory_mutex_master_hps_0 configuration
 *
 */

#define ALT_MODULE_CLASS_shared_memory_mutex_master_hps_0 altera_avalon_mutex
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_BASE 0x50000
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_IRQ -1
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_NAME "/dev/shared_memory_mutex_master_hps_0"
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_OWNER_INIT 1
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_OWNER_WIDTH 16
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_SPAN 8
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_TYPE "altera_avalon_mutex"
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_VALUE_INIT 1
#define SHARED_MEMORY_MUTEX_MASTER_HPS_0_VALUE_WIDTH 16


/*
 * shared_memory_mutex_master_nios_0 configuration
 *
 */

#define ALT_MODULE_CLASS_shared_memory_mutex_master_nios_0 altera_avalon_mutex
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_BASE 0x80000
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_IRQ -1
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_NAME "/dev/shared_memory_mutex_master_nios_0"
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_OWNER_INIT 3
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_OWNER_WIDTH 16
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_SPAN 8
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_TYPE "altera_avalon_mutex"
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_VALUE_INIT 1
#define SHARED_MEMORY_MUTEX_MASTER_NIOS_0_VALUE_WIDTH 16


/*
 * spi_0 configuration
 *
 */

#define ALT_MODULE_CLASS_spi_0 altera_avalon_spi
#define SPI_0_BASE 0x20
#define SPI_0_CLOCKMULT 1
#define SPI_0_CLOCKPHASE 0
#define SPI_0_CLOCKPOLARITY 0
#define SPI_0_CLOCKUNITS "Hz"
#define SPI_0_DATABITS 8
#define SPI_0_DATAWIDTH 16
#define SPI_0_DELAYMULT "1.0E-9"
#define SPI_0_DELAYUNITS "ns"
#define SPI_0_EXTRADELAY 0
#define SPI_0_INSERT_SYNC 0
#define SPI_0_IRQ 5
#define SPI_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_0_ISMASTER 1
#define SPI_0_LSBFIRST 0
#define SPI_0_NAME "/dev/spi_0"
#define SPI_0_NUMSLAVES 3
#define SPI_0_PREFIX "spi_"
#define SPI_0_SPAN 32
#define SPI_0_SYNC_REG_DEPTH 2
#define SPI_0_TARGETCLOCK 24000000u
#define SPI_0_TARGETSSDELAY "0.0"
#define SPI_0_TYPE "altera_avalon_spi"


/*
 * sysid_fpga configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_fpga altera_avalon_sysid_qsys
#define SYSID_FPGA_BASE 0x10000
#define SYSID_FPGA_ID 17047575
#define SYSID_FPGA_IRQ -1
#define SYSID_FPGA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_FPGA_NAME "/dev/sysid_fpga"
#define SYSID_FPGA_SPAN 8
#define SYSID_FPGA_TIMESTAMP 1496839578
#define SYSID_FPGA_TYPE "altera_avalon_sysid_qsys"


/*
 * timer_0_nios2 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0_nios2 altera_avalon_timer
#define TIMER_0_NIOS2_ALWAYS_RUN 1
#define TIMER_0_NIOS2_BASE 0x0
#define TIMER_0_NIOS2_COUNTER_SIZE 32
#define TIMER_0_NIOS2_FIXED_PERIOD 1
#define TIMER_0_NIOS2_FREQ 50000000
#define TIMER_0_NIOS2_IRQ 2
#define TIMER_0_NIOS2_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_NIOS2_LOAD_VALUE 49999
#define TIMER_0_NIOS2_MULT 0.001
#define TIMER_0_NIOS2_NAME "/dev/timer_0_nios2"
#define TIMER_0_NIOS2_PERIOD 1
#define TIMER_0_NIOS2_PERIOD_UNITS "ms"
#define TIMER_0_NIOS2_RESET_OUTPUT 0
#define TIMER_0_NIOS2_SNAPSHOT 1
#define TIMER_0_NIOS2_SPAN 32
#define TIMER_0_NIOS2_TICKS_PER_SEC 1000
#define TIMER_0_NIOS2_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_NIOS2_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
